version: '3'
services:
  front:
    image: "nginx-front:alpine"
    ports:
      - "443:443"
    volumes:
      - /Users/nikhil/Documents/nginx/setup/nginx:/etc/nginx
  back1:
    image: "nginx-back1:alpine"
    ports:
      - "8090:80"
  back2:
    image: "nginx-back2:alpine"
    ports:
      - "8095:80"
